export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Gbeminiyin Ajayi",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "Idowu Peters",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Victor Oti",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Chika Osuocha",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpeg",
    username: "Thomas Holden",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "Uzoamaka Ajayi",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Alabi Adenekan",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Babajide Oyelami",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Bakare William",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Tolu Awoniyi",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    firstName: "Alabi",
    lastName: "Adenekan",
    userId: 1,
    like: 32,
    comment: 9,
    userPicturePath: "assets/person/1.jpeg",
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    firstName: "Gbeminiyi",
    lastName: "Ajayi",
    like: 2,
    comment: 1,
    userPicturePath: "assets/person/2.jpeg",
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    firstName: "Bakare",
    lastName: "Williams",
    userId: 3,
    like: 61,
    comment: 2,
    userPicturePath: "assets/person/3.jpeg",
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    firstName: "Joe",
    lastName: "Brad",
    like: 7,
    comment: 3,
    userPicturePath: "assets/person/4.jpeg",
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    firstName: "Price",
    lastName: "Cook",
    like: 23,
    comment: 5,
    userPicturePath: "assets/person/5.jpeg",
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    firstName: "King",
    lastName: "Palance",
    like: 44,
    comment: 6,
    userPicturePath: "assets/person/6.jpeg",
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    firstName: "Lord",
    lastName: "Bright",
    userId: 7,
    like: 52,
    comment: 3,
    userPicturePath: "assets/person/7.jpeg",
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    firstName: "Fisher",
    lastName: "Grass",
    like: 15,
    comment: 1,
    userPicturePath: "assets/person/8.jpeg",
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    firstName: "Martins",
    lastName: "Jasse",
    like: 11,
    comment: 2,
    userPicturePath: "assets/person/9.jpeg",
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    firstName: "Deji",
    lastName: "Akinlabi",
    like: 104,
    comment: 12,
    userPicturePath: "assets/person/10.jpeg",
  },
];
